export { VentanasTab } from "./VentanasTab"
export { MaterialesTab } from "./MaterialesTab"
export { OptimizacionTab } from "./OptimizacionTab"
export { DeleteProjectDialog } from "./DeleteProjectDialog"
export { DeleteWindowDialog } from "./DeleteWindowDialog"
